name: Build scripts
on:
  release:
    types: [published]

  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "latest"

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.IMG_NAME  }}:${{ inputs.version }}
